---
title: "igraph Code for Event Data"
author: "Marcus Sianan"
date: "8/29/2022"
output:
  html_document: default
  pdf_document: default
---

```{r}
#Install packages

install.packages("devtools")
install.packages("UTDEventData")
install.packages("jsonlite")
install.packages("jsonify")
install.packages("dplyr")
install.packages("igraph")
```

```{r}
#Load libraries

library(devtools)
library(UTDEventData)
library(jsonlite)
library(jsonify)
library(dplyr)
library(igraph)
```

```{r}
#Pull data

#December 2021
data <- jsonlite::fromJSON("https://eventdata.utdallas.edu/api/data?api_key=DuKE0xxIVofZfbzWjmfgGwQc3UM8JR63&query={%22$and%22:[{%22country_code%22:{%22$in%22:[%22USA%22,%22DEU%22,%22GBR%22,%22RUS%22,%22UKR%22,%22CHN%22,%22IND%22,%22TUR%22,%22BLR%22]}},{%22date8%22:{%22$gte%22:%2220211201%22,%22$lte%22:%2220211231%22}}]}&datasource=phoenix_v3")

#January 2022
#data <- jsonlite::fromJSON("https://eventdata.utdallas.edu/api/data?api_key=DuKE0xxIVofZfbzWjmfgGwQc3UM8JR63&query={%22$and%22:[{%22country_code%22:{%22$in%22:[%22USA%22,%22DEU%22,%22GBR%22,%22RUS%22,%22UKR%22,%22CHN%22,%22IND%22,%22TUR%22,%22BLR%22]}},{%22date8%22:{%22$gte%22:%2220220101%22,%22$lte%22:%2220220131%22}}]}&datasource=phoenix_v3")

#February 2022
#data <- jsonlite::fromJSON("https://eventdata.utdallas.edu/api/data?api_key=DuKE0xxIVofZfbzWjmfgGwQc3UM8JR63&query={%22$and%22:[{%22country_code%22:{%22$in%22:[%22USA%22,%22DEU%22,%22GBR%22,%22RUS%22,%22UKR%22,%22CHN%22,%22IND%22,%22TUR%22,%22BLR%22]}},{%22date8%22:{%22$gte%22:%2220220201%22,%22$lte%22:%2220220228%22}}]}&datasource=phoenix_v3")

#March 2022
#data <- jsonlite::fromJSON("https://eventdata.utdallas.edu/api/data?api_key=DuKE0xxIVofZfbzWjmfgGwQc3UM8JR63&query={%22$and%22:[{%22country_code%22:{%22$in%22:[%22USA%22,%22DEU%22,%22GBR%22,%22RUS%22,%22UKR%22,%22CHN%22,%22IND%22,%22TUR%22,%22BLR%22]}},{%22date8%22:{%22$gte%22:%2220220301%22,%22$lte%22:%2220220331%22}}]}&datasource=phoenix_v3")

#April 2022
#data <- jsonlite::fromJSON("https://eventdata.utdallas.edu/api/data?api_key=DuKE0xxIVofZfbzWjmfgGwQc3UM8JR63&query={%22$and%22:[{%22country_code%22:{%22$in%22:[%22USA%22,%22DEU%22,%22GBR%22,%22RUS%22,%22UKR%22,%22CHN%22,%22IND%22,%22TUR%22,%22BLR%22]}},{%22date8%22:{%22$gte%22:%2220220401%22,%22$lte%22:%2220220430%22}}]}&datasource=phoenix_v3")
```

```{r}
#Configure dataframes

df1 <- data.frame(data) 

df2 <- data.frame(df1$data.src_actor, df1$data.tgt_actor, df1$data.root_code)

#Group by cooperative events
df3 <- filter(df2, df1$data.root_code %in% c('03', '04', '05', '06', '07', '08'))

#Or, group by conflict events
#df3 <- filter(df2, df1$data.root_code %in% c('09', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20'))

#Extract USA, DEU, GBR, RUS, UKR, CHN, IND, and TUR as actor pairs from "src_actor" and "tgt_actor" categories 
df4 <- filter(df3, df1.data.src_actor %in% c('USA', 'DEU', 'GBR', 'RUS', 'UKR', 'CHN', 'IND', 'TUR'))
df5 <- filter(df4, df1.data.tgt_actor %in% c('USA', 'DEU', 'GBR', 'RUS', 'UKR', 'CHN', 'IND', 'TUR'))

#Create dataframe sorted alphabetically over source actor (to take control back from igraph's node positioning)
df6 <- df5[order(df5$df1.data.src_actor), , drop = FALSE]
```

```{r}
#Create graph object

g <- graph_from_data_frame(df6)
```

```{r}
#Color specific nodes

V(g)["USA"]$color <- "lightblue"
V(g)["DEU"]$color <- "lightblue"
V(g)["GBR"]$color <- "lightblue"
V(g)["TUR"]$color <- "lightblue"
V(g)["RUS"]$color <- "red"
V(g)["UKR"]$color <- "yellow"
```

```{r}
#Plot

plot(g,
     main = "Countries by src_actor and tgt_actor: Dec. 1 - Dec. 31, 2021",
     edge.arrow.size = .5,
     edge.arrow.width = .6, 
     edge.color = "gray", 
     vertex.label.cex = 0.8,
     edge.width = E(g)$weight,
     order = V(g),
     layout=layout_in_circle)

legend("bottomleft",legend=c("Ukraine", "Russia", "NATO"),fill=c("yellow","red","lightblue"))
```
